# Generated by Django 4.1.3 on 2022-11-06 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaPyme',
            fields=[
                ('idPyme', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Pyme')),
                ('nombrePyme', models.CharField(max_length=50, verbose_name='Nombre Pyme')),
                ('rutPyme', models.CharField(max_length=12, verbose_name='Rut Pyme')),
                ('bancoPyme', models.CharField(choices=[('CHI', 'Banco de Chile'), ('SAN', 'Banco Santander-Santiago'), ('SCO', 'Banco Scotiabank'), ('EST', 'Banco del Estado de Chile'), ('FAL', 'Banco Falabella'), ('DES', 'Banco del Desarrollo'), ('BIC', 'Banco Bice'), ('CON', 'Banco Consorcio'), ('BCI', 'Banco de Credito e Inversiones'), ('ITA', 'Banco Itau'), ('SEC', 'Banco Security'), ('CIT', 'Citibank N.A'), ('INT', 'Banco Internacional')], max_length=4, verbose_name='Banco Pyme')),
                ('tipoCuentaPyme', models.CharField(choices=[('COR', 'Cuenta Corriente/Cuenta Vista'), ('AHOR', 'Cuenta Ahorro')], max_length=4, verbose_name='Tipo cuenta Banco Pyme')),
                ('cuentaBancoPyme', models.CharField(max_length=15, verbose_name='Cuenta Bancaria Pyme')),
                ('correoPyme', models.CharField(max_length=100, verbose_name='Email Pyme')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Producto')),
                ('nombreProducto', models.CharField(max_length=50, verbose_name='Nombre Producto')),
                ('descripcionProducto', models.CharField(max_length=500, verbose_name='Descripcion Producto')),
                ('activoProducto', models.BooleanField(default=True, verbose_name='active')),
                ('precioProducto', models.PositiveIntegerField(verbose_name='Precio Producto')),
                ('imagenProducto', models.ImageField(upload_to='static/images/upload/')),
                ('stockProducto', models.PositiveIntegerField(verbose_name='Stock Producto')),
                ('categoriaProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('pymeProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresapyme')),
            ],
        ),
    ]
