# Generated by Django 4.1.3 on 2022-11-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresapyme',
            name='correoPyme',
            field=models.EmailField(max_length=100, verbose_name='Email Pyme'),
        ),
    ]
