# Generated by Django 4.1.3 on 2022-11-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_empresapyme_correopyme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcionProducto',
            field=models.TextField(max_length=500, verbose_name='Descripcion Producto'),
        ),
    ]
