# Generated by Django 4.1.3 on 2022-11-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_producto_descripcionproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Cliente')),
                ('rutCliente', models.CharField(max_length=12, verbose_name='Rut Cliente')),
                ('nombreCliente', models.CharField(max_length=50, verbose_name='Nombre Cliente')),
                ('apellidoCliente', models.CharField(max_length=50, verbose_name='Apellido Cliente')),
                ('correoCliente', models.EmailField(max_length=50, verbose_name='Correo Cliente')),
                ('direccionCliente', models.CharField(max_length=50, verbose_name='Direccion Cliente')),
                ('telefonoCliente', models.CharField(max_length=9, verbose_name='Telefono Cliente')),
            ],
        ),
    ]
